apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hub-docs
  title: HUB Docs
  description: Canonical HUB governance + operational runbook (TechDocs)
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: user:danie
